// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHnNsqu0JueVbJHomjV3PFlxz2JMPYCNA',
    appId: '1:704779599443:web:3ce62a706219d74dd710a6',
    messagingSenderId: '704779599443',
    projectId: 'gym-buddy-7202c',
    authDomain: 'gym-buddy-7202c.firebaseapp.com',
    storageBucket: 'gym-buddy-7202c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVdeMprUhdcncxVet-c4Acu4gZ5eX1fDY',
    appId: '1:704779599443:android:e4b072a1b699cfb7d710a6',
    messagingSenderId: '704779599443',
    projectId: 'gym-buddy-7202c',
    storageBucket: 'gym-buddy-7202c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEs4-5kSpoGgvFdBXaBPq9FmIEJimChxc',
    appId: '1:704779599443:ios:8d12832cb2322a22d710a6',
    messagingSenderId: '704779599443',
    projectId: 'gym-buddy-7202c',
    storageBucket: 'gym-buddy-7202c.appspot.com',
    iosClientId: '704779599443-gtcbnmkkjc53kf9gegqvhco1me5n4bgc.apps.googleusercontent.com',
    iosBundleId: 'com.gymwithbudz.app',
  );
}
